date = "2017-12-24"

en = """
Finished battery #3, ьзмы╜Х.  It started as a hodgepodge of leftover parts.  I had extra blood gelatin that I didn't want to waste, and a bunch of glass, so I threw them together to form the new battery.  The form is pretty myeh.  It looks like a tongue, which is not a problem per se. I didn't have a particular message in mind when making it, it was more a study of form.
"""

kr = """
"""

images = ["jjambbong/3-light.jpg"]

tags = ["blood batteries"]