date = "2017-12-30"

en = """
Worked on documentation.  Cleaned up photos for Family Portrait and created a cinemagraph of the single stack figure.
"""

kr = """
작품의 문서화위해 일했다. Family Portrait (가족 사진)의 사진을 편집하고, 단독상 존재를 cinemagraph으로 만들었다.
"""

images = []

tags = ["cinemagraph", "blood batteries"]