date = "2017-12-05"

en = """
Worked on a tiered battery combining cells in parallel and series. The experiment was a partial success. Voltage increased as expected with added layers, however current decreased slightly. I suspect the parallel stacking is not effective electrochemically, though it may still be worth pursuing for visual effect.
\n
Worked on repairing the dissected dog toy. Discovered I was missing several crucial parts so it is not salvageable without 3D printing or otherwise obtaining the missing pieces. The cost would not be worth the effort.
\n
Looking into cheap stepper motors as a possible alternative.
"""

kr = """
"""

images = ["blog/Dec5.jpg"]

tags = ["blood batteries", "electronics"]