date = "2017-12-18"

en = """
Began working on 이조바위 and the sculptural battery. The teeth look quite good. I'm trying to figure out how to fix them to the hat structure. I'm also deciding 1) if I should create new teeth from resin or just use the plastic teeth, 2) if I should use paper or another material for the 조바위, 3) what type of adhesive I should use.
\n
The sculptural battery didn't look very good in the mock up. I went ahead and began cutting the electrodes. I hope it looks better once it's finished. The cuts are _very_ jagged. I looked at waterjet cutting which would be a much cleaner option, but I don't think I want to spend the money on that quite yet.
"""

kr = """
"""

images = ["teeth/prototype_clay.jpg"]

tags = ["teeth", "blood batteries", "process"]