date = "2017-11-12"

en = """
Mostly math today. I received my eyes. They work as expected, though I realize now as I tip them back and forth that it will not have the behavior I want. Because the eyes need to be tipped back to shut, they do not look like they are closing. It simply looks like they are rolling away. I am going to try using a thin thread to pull the eyes shut, but am not sure this will look as I want it to.
\n
I also drew one circuit diagram. I drew the conductive touch circuit that I've been using with the ATTiny.
"""

kr = """
"""

images = []

tags = ["math", "electronics"]