date = "2017-12-20"

en = """
Sometimes it seems like half my art is about Googling for supplies.  Today I looked into different types of moldable plastic for the 조바위.  I flattened the electrodes and sorted them.  I am thawing blood and will finish the first sculptural battery tomorrow.
"""

kr = """
"""

images = []

tags = ["blood batteries", "process"]