date = "2017-12-21"

en = """
Made a large batch of blood gelatin. I'm still perfecting the recipe. I had to add a lot more water than I originally intended. In the future, I will need to make smaller batches of gelatin mix and aggregate them instead of trying to do one big batch. Adding a full packet of gelatin to a small amount of water causes the gelatin to solidify into a big clump instead of dissolving into the water. 
\n
The blood gelled nicely despite the clumpy gelatin mix. Some bubbles, but mostly very smooth and even. I cut out the patties today and took lots of process photos. I'm losing light so I'll finish assembling the batteries tomorrow.
"""

kr = """
"""

images = ["blog/IMG_20171221_150149-cropped.jpg"]

tags = ["blood batteries", "process"]