date = "2017-12-29"

en = """
Attempted my first body cast.  I created a mold from the lower half of my face, then cast the mold in plaster.  The cast leaves much to be desired.  There is alginate and cloth caught around the nostrils, and the face is deformed around my nose.  For future casts I think it would be better to cast my whole face, and then divide it into a smaller section later, or to trim the alginate and plaster bandages and create some sort of barrier before casting the plaster.
"""

kr = """
첫 body cast (몸의 주형)을 만들어 보았다. 먼저, 얼굴 반의 주형을 만들었다. 저형을 잘 나오지 않았다. 콧구멍에 plaster와 alginate가 끼었고, 코근처의 주형이 변형되었다. 다음에는 주형을 만들 때 얼굴 전체의 주형을 만든 후 나누거나, plaster를 주형하기 전에 alginate과 plaster를 먼저 정리하면 좋을 것 같다.
"""

images = []

tags = ["cast"]