date = "2018-01-02"

en = """
Made a cast of Haan's face.  Created a plaster cast from the alginate without any plaster support structure so it's a weird, flat face.  Forgot to fill the nostrils with alginate again, so I filled them with playdough.  Worked out.
"""

kr = """
한의 얼굴의 주형을 만들어 보았다.  plaster의 지지구조물을 안 하였기때문에 섬뜻한 느낌의 납작한 얼굴이 되었다.  콧구멍을 alginate으로 막는것을 잊어서 playdough로 막았다.괜찮았다.
"""

images = []

tags = ["blood batteries", "face", "cast"]