date = "2018-09-01"

en = """
Made A LOT of progress on moving my github site to flask. I have dynamic urls and templates for my artwork and series pages. Did a bit of pair programming which was great.  Really loving recurse center so far!
"""

kr = """
github 웹사이트를 플라스크로 옮기는 것이 꽤 진전됐다. dynamic urls과 작품와 시리즈의 페이지로 템플릿으로 만들었다. 다른 사람과 같이 프로그래밍을 조금했고 너무 좋았다.  지금 까지 recurse center은 정말 좋았한!
"""

images = []

tags = ["recurse", "flask"]