date = "2017-12-19"

en = """
Continue work on sculptural battery. Cutting zinc electrodes.
\n
Bought new cup for blood collection. Wasted a lot figuring out how to collect, but getting the hang of it now.
"""

kr = """
"""

images = []

tags = ["blood batteries", "process"]