date = "2017-06-12"

en = """
Tested a simple servo motor sketch to dip a teabag. Should be straightforward to adapt this sketch to move a shaft back and forth to cause eyes to open and close.     
\n
Spent most of the afternoon on the capacitive touch sensor. I was not able to recreate the effect I saw at the showcase. At the time, I had though the large copper tape was acting as a huge resistor and making the touch sensor incredibly sensitive. The light would begin to flicker when I was about 4-5 ft away and would get brighter until it was fully lit when I was close to the pedestal. I did not record the effect.
\n
I tried to recreate the circuit. I used an ATTINY45 and a large copper sheet connected to the sensor pin. When the copper was connected, the light would remain on and at full brightness. The effect did not change when I moved away. I have no idea why it worked at the showcase.
\n
I moved on to the capsense library and created a distance sensor that mimicked the effect described above. However, it is not nearly as sensitive as the sensor I had at the showcase. I wish I knew how to recreate the effect.
\n
I added a servo motor to the capsense sensor, but the motion is quite jittery since the capacitive sensor has a large bounce. I added some crude de-bouncing code, but it did not completely erase the jitter.
"""

kr = """
"""

images = ["<a href='http://www.youtube.com/watch?feature=player_embedded&v=b_B9V2F4Smo' target='_blank'><img src='http://img.youtube.com/vi/b_B9V2F4Smo/0.jpg' alt='video 1 of tea robot'/></a>", "<a href='http://www.youtube.com/watch?feature=player_embedded&v=7PeKho2plbE' target='_blank'><img src='http://img.youtube.com/vi/7PeKho2plbE/0.jpg' alt='video 2 of tea robot'/></a>"]

tags = ["electronics", "capacitive touch"]