date = "2018-06-01"

en = """
Created a new sculpture with Haan's face cast.  Came out great.  The large strips of metal behind the face are quite nice aesthetically.  I would like to do this again waay bigger in a grid and power a larger device.
"""

kr = """
한의 얼굴의 주형으로 조각을 만들었다. 잘 나왔다. 얼굴 뒤에 있는 구리와 아연이 미적으로 보기 좋다. 전기를 더 많이 사용하는 작품을 만들고싶어 같은 모양의 조각상을 훨씬 크게 만들고 싶다.
"""

images = []

tags = ["blood batteries", "face", "sculpture"]